name             'packer_kvm'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures packer_kvm'
long_description 'Installs/Configures packer_kvm'
version          '0.2.1'
depends          'docker_wrapper'
depends          'ntp'
depends          'resolver'
depends	         'network_interfaces_wrapper'
depends          'nfs_export_wrapper'
depends          'autofs_wrapper'
