name             'packer_kvm'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures packer_kvm'
long_description 'Installs/Configures packer_kvm'
version          '0.2.0'
depends          'hostname'
depends          'docker_wrapper'
depends          'ntp'
depends	         'serial_console'
depends	         'network_interfaces_wrapper'
