source "https://supermarket.chef.io"

metadata

cookbook 'chef-client'
cookbook 'docker_wrapper', git: 'https://github.com/randomcoww/chef-docker_wrapper.git'
cookbook 'vpn_config', git: 'https://github.com/randomcoww/chef-vpn_config.git'
