---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    driver:
      network:
        - ["private_network", {type: "dhcp", mac: "0025B55B0019", auto_config: false}]
        - ["private_network", {type: "dhcp", mac: "0025B55B0017", auto_config: false}]
  - name: centos-6.6
    driver:
      network:
        - ["private_network", {type: "dhcp", mac: "0025B55B0023", auto_config: false}]
        - ["private_network", {type: "dhcp", mac: "0025B55B0021", auto_config: false}]
  - name: win-2012r2
    driver:
      box: opentable/win-2012r2-standard-amd64-nocm
      network:
        - ["forwarded_port", {guest: 3389, host: 3389}]
        - ["private_network", {type: "dhcp", mac: "0025B55B0025", auto_config: false}]
        - ["private_network", {type: "dhcp", mac: "0025B55B0027", auto_config: false}]
        - ["private_network", {type: "dhcp", mac: "0025B55B0029"}]

suites:
  - name: default
    run_list:
      - recipe[fake::default]
  - name: default-chef11
    run_list:
      - recipe[fake::default]
    provisioner:
      require_chef_omnibus: 11.18.6

  - name: bonding
    run_list:
      - recipe[fake::bonding]
    excludes:
      - win-2012r2
  - name: bonding-chef11
    run_list:
      - recipe[fake::bonding]
    excludes:
      - win-2012r2
    provisioner:
      require_chef_omnibus: 11.18.6

  - name: vlan
    run_list:
      - recipe[fake::vlan]
  - name: vlan-chef11
    run_list:
      - recipe[fake::vlan]
    provisioner:
      require_chef_omnibus: 11.18.6

  - name: bridge
    run_list:
      - recipe[fake::bridge]
    excludes:
      -win-2012r2
  - name: bridge-chef11
    run_list:
      - recipe[fake::bridge]
    excludes:
      -win-2012r2
    provisioner:
      require_chef_omnibus: 11.18.6
