---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6

suites:
  - name: nfs-test
    run_list:
      - recipe[nfs_test::default]
  - name: nfs-only-test
    run_list:
      - recipe[nfs_only::default]
  - name: auto_master
    run_list:
      - recipe[auto_master::default]
