language: ruby
bundler_args: --without development
script: "bundle exec rake style"
rvm:
  - 2.1.4 
gemfile:
  - Gemfile
branches:
  only:
    - master
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fe9ba3e83b70f4a9ffe1 
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
